name: Deploy to Azure Functions

on:
  pull_request_target:
    types: [closed]
    branches: [ main, working ]
    paths:
      - 'api/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: |
        cd api
        npm ci --no-audit
      timeout-minutes: 10
    
    - name: Run unit tests
      run: |
        cd api
        npm test
      timeout-minutes: 5
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      timeout-minutes: 10
    
    - name: Prepare deployment structure
      run: |
        # 清理 deployment 目录
        rm -rf deployment
        mkdir -p deployment
        # 只复制 health 目录下的 index.js 和 function.json 到 deployment 根目录
        cp api/health/index.js deployment/
        cp api/health/function.json deployment/
        # 显示结构
        echo "Deployment structure:"
        ls -la deployment/
      timeout-minutes: 5
    
    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true
      timeout-minutes: 10
        
    - name: Deploy to Azure Functions
      run: |
        # Deploy from the prepared deployment directory
        cd deployment
        func azure functionapp publish chatbotprocessor --javascript --force
      timeout-minutes: 20
        
    - name: Restart Function App
      run: |
        # Restart the function app to ensure new files are loaded
        az functionapp restart --name chatbotprocessor --resource-group ResourceGroup1
      timeout-minutes: 5 