name: Test the pull request for GitHub Pages

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/**'
  pull_request_target:
    types: [closed]
    branches: [ main, working ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      pull-requests: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_PAT }}

      - name: Check for existing PR
        env:
          GH_TOKEN: ${{ secrets.ACTION_PAT }}
        run: |
          # Get the current branch name
          BRANCH_NAME="working"
          
          # Check if a PR already exists for this branch
          PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --json number --jq 'length')
          
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          if [ "$PR_EXISTS" -eq 0 ]; then
            echo "No PR exists for branch $BRANCH_NAME"
          else
            echo "PR already exists for branch $BRANCH_NAME"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run tests
        run: npm run test

 