name: Deploy Azure Functions

on:
  pull_request_target:
    types: [closed]
    branches: [ main, working ]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    - name: Run unit tests
      run: |
        cd api
        npm test

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    - name: Run unit tests
      run: |
        cd api
        npm test
    
    - name: Prepare deployment package
      run: |
        # Create deployment directory
        mkdir -p deployment
        # Copy all files from api directory to deployment root
        cp -r api/* deployment/
        # Ensure host.json is at the root level
        ls -la deployment/
        echo "Deployment package structure:"
        find deployment/ -type f -name "*.json" | head -10
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'chatbotprocessor'
        package: './deployment'
        respect-pom-xml: false
        respect-funcignore: false
        scm-do-build-during-deployment: false
        enable-oryx-build: false
        remote-build: false
    
 