name: Test the pull request for Azure Functions

on:
  pull_request_target:
    types: [closed]
    branches: [ main, working ]
    paths:
      - 'api/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    - name: Run unit tests
      run: |
        cd api
        npm test


    

    
 