name: Deploy to Azure Functions

on:
  pull_request_target:
    types: [closed]
    branches: [ main, working ]
    paths:
      - 'api/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.merged == true
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    
    - name: Install dependencies
      run: |
        cd api
        npm ci
    
    - name: Run unit tests
      run: |
        cd api
        npm test
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Prepare deployment structure
      run: |
        # Create a deployment directory with correct structure
        mkdir -p deployment
        # Copy host.json to root (Azure Functions expects it here)
        cp api/host.json deployment/
        # Copy function directories
        cp -r api/health deployment/
        cp -r api/process deployment/
        # Copy package files
        cp api/package.json deployment/
        cp api/package-lock.json deployment/
        # Copy source files
        cp -r api/src deployment/
        # Show the structure
        echo "Deployment structure:"
        ls -la deployment/
        echo "host.json location:"
        find deployment/ -name "host.json"
        echo "Health function structure:"
        ls -la deployment/health/
        echo "Process function structure:"
        ls -la deployment/process/
    

        
    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true
        
    - name: Deploy to Azure Functions
      run: |
        # Deploy from the prepared deployment directory
        cd deployment
        func azure functionapp publish chatbotprocessor --javascript
        
    - name: Restart Function App
      run: |
        # Restart the function app to ensure new files are loaded
        az functionapp restart --name chatbotprocessor --resource-group ResourceGroup1 