name: Test and Deploy Backend

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  test-and-deploy-backend:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
        
    - name: Install API dependencies
      run: |
        cd api
        npm ci
        
    - name: Run API tests
      run: |
        cd api
        npm test
        
    - name: Validate Azure Functions
      run: |
        cd api
        npm run lint
        
    - name: Build Azure Functions package
      run: |
        cd api
        func pack --build remote --force
        
    - name: Upload Azure Functions package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: azure-functions-production-package
        path: api/api.zip
        retention-days: 90
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'chatbotprocessor'
        package: './api/api.zip' 